version: "3.9"

services:
  db:
    image: postgres:15
    container_name: donations_db
    restart: always
    environment:
      POSTGRES_DB: donations
      POSTGRES_USER: donations_user
      POSTGRES_PASSWORD: donations_pass
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: donations_backend
    command: sh -c "/wait-for-postgres.sh db echo 'Postgres listo' && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_NAME: donations
      DATABASE_USER: donations_user
      DATABASE_PASSWORD: donations_pass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: donations_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
